import './globals.css'
import {FcViewDetails } from "react-icons/fc";

export const metadata = {
  title: '메모장',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="container mx-auto">
          <header className="flex justify-center text-center p-10 border-b border-gray-400 font-bold text-6xl">
          <FcViewDetails className='logo'/> MEMO LIST <FcViewDetails className='logo'/>
          </header>
          <div className="grid grid-rows-4 gap-2">
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
